### ISSUE TITLE
No alignments for images

### ISSUE THREAD

**Issue by dismine** [asciidoctor/asciidoctor-fb2#16]
Hi.

Thank you for this opportunity to be able to create fb2 version of my document.

As I understood there is no support for _align_ attribute.

Usually, I do something like this

`image::images/my-image.png[pdfwidth=95%, scaledwidth=60%, align="center"]`

**Comment by dismine** [comment]
_scaledwidth_ also seems doesn't work.

**Comment by slonopotamus** [comment]
http://www.fictionbook.org/index.php/%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82_image

The only image attributes that FB2 has are: alt/title/id.

There's optional support for CSS stylesheets (http://www.fictionbook.org/index.php/%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82_stylesheet) but I have no idea if there are any existing readers that actually have it.

**Comment by dismine** [comment]
Okay. It seems how will looks images highly dependent on a reader.

**Comment by slonopotamus** [comment]
So. We definitely can do *something* via CSS. See ceee816389d7b8ac8b7966995edce295be0e01fb.
