### ISSUE TITLE
Admonition icons

### ISSUE THREAD

**Issue by dismine** [asciidoctor/asciidoctor-fb2#18]
Is it possible to replace words for admonition types with something better? For example images like asciidoctor-pdf or asciidoctor-epub do.

**Comment by slonopotamus** [comment]
There are three modes for admonitions in HTML/PDF backend:

1. Text (default)
2. Font-based icons via `:icons: font` document attribute
3. Image-based icons via `:icons:` document attribute. Note that icon images are not provided by Asciidoctor.

Interestingly, EPUB backend only does second option regardless of `:icons:` attribute.

FB2 currently only does first option.
